// <auto-generated />
using System;
using LibraryCatalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryCatalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LibraryCatalogDbContext))]
    partial class LibraryCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryCatalog.Domain.Entities.Autor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Autores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000001"),
                            Nombre = "Gabriel García Márquez"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000002"),
                            Nombre = "Isabel Allende"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000003"),
                            Nombre = "Jorge Luis Borges"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000004"),
                            Nombre = "Julio Verne"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000005"),
                            Nombre = "Robert C. Martin"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-4000-8000-000000000006"),
                            Nombre = "Yuval Noah Harari"
                        });
                });

            modelBuilder.Entity("LibraryCatalog.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-4000-8000-000000000001"),
                            Nombre = "Novela"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-4000-8000-000000000002"),
                            Nombre = "Cuento"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-4000-8000-000000000003"),
                            Nombre = "Ciencia ficción"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-4000-8000-000000000004"),
                            Nombre = "Ingeniería de software"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-4000-8000-000000000005"),
                            Nombre = "Historia"
                        });
                });

            modelBuilder.Entity("LibraryCatalog.Domain.Entities.Libro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Libros", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000001"),
                            AnioPublicacion = 1967,
                            AutorId = new Guid("a0000000-0000-4000-8000-000000000001"),
                            CategoriaId = new Guid("c0000000-0000-4000-8000-000000000001"),
                            ISBN = "9788439700012",
                            Titulo = "Cien años de soledad"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000002"),
                            AnioPublicacion = 1985,
                            AutorId = new Guid("a0000000-0000-4000-8000-000000000001"),
                            CategoriaId = new Guid("c0000000-0000-4000-8000-000000000001"),
                            ISBN = "9788439700029",
                            Titulo = "El amor en los tiempos del cólera"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000003"),
                            AnioPublicacion = 1982,
                            AutorId = new Guid("a0000000-0000-4000-8000-000000000002"),
                            CategoriaId = new Guid("c0000000-0000-4000-8000-000000000001"),
                            ISBN = "9788498385014",
                            Titulo = "La casa de los espíritus"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000004"),
                            AnioPublicacion = 1944,
                            AutorId = new Guid("a0000000-0000-4000-8000-000000000003"),
                            CategoriaId = new Guid("c0000000-0000-4000-8000-000000000002"),
                            ISBN = "9789500401012",
                            Titulo = "Ficciones"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000005"),
                            AnioPublicacion = 1949,
                            AutorId = new Guid("a0000000-0000-4000-8000-000000000003"),
                            CategoriaId = new Guid("c0000000-0000-4000-8000-000000000002"),
                            ISBN = "9789500401029",
                            Titulo = "El Aleph"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000006"),
                            AnioPublicacion = 1870,
                            AutorId = new Guid("a0000000-0000-4000-8000-000000000004"),
                            CategoriaId = new Guid("c0000000-0000-4000-8000-000000000003"),
                            ISBN = "9788413229713",
                            Titulo = "Veinte mil leguas de viaje submarino"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000007"),
                            AnioPublicacion = 1865,
                            AutorId = new Guid("a0000000-0000-4000-8000-000000000004"),
                            CategoriaId = new Guid("c0000000-0000-4000-8000-000000000003"),
                            ISBN = "9788413229720",
                            Titulo = "De la Tierra a la Luna"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000008"),
                            AnioPublicacion = 2008,
                            AutorId = new Guid("a0000000-0000-4000-8000-000000000005"),
                            CategoriaId = new Guid("c0000000-0000-4000-8000-000000000004"),
                            ISBN = "9780132350884",
                            Titulo = "Clean Code"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000009"),
                            AnioPublicacion = 2017,
                            AutorId = new Guid("a0000000-0000-4000-8000-000000000005"),
                            CategoriaId = new Guid("c0000000-0000-4000-8000-000000000004"),
                            ISBN = "9780134494166",
                            Titulo = "Clean Architecture"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-4000-8000-000000000010"),
                            AnioPublicacion = 2011,
                            AutorId = new Guid("a0000000-0000-4000-8000-000000000006"),
                            CategoriaId = new Guid("c0000000-0000-4000-8000-000000000005"),
                            ISBN = "9788466333412",
                            Titulo = "Sapiens: de animales a dioses"
                        });
                });

            modelBuilder.Entity("LibraryCatalog.Domain.Entities.Libro", b =>
                {
                    b.HasOne("LibraryCatalog.Domain.Entities.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryCatalog.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Libros")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("LibraryCatalog.Domain.Entities.Autor", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("LibraryCatalog.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
